version: 2
jobs:
  build:
    docker: # Executor タイプです。他に machine、macOS という実行タイプを指定できます
      - image: hsnuhayato/choreonoid1.7 # プライマリコンテナです。このなかでジョブコマンドが実行されます
    steps:
      - checkout # プロジェクトのディレクトリにあるコードをチェックアウトします
      
      - run:
          name: checkout and build
          command: git clone https://github.com/hsnuhayato/tsml -b wu_branch

